version: "3.2"
services: 
  postgres:
    hostname: postgres
    container_name: postgres
    image: postgres:13
    restart: always
    ports: 
      - "5432:5432"
    environment: 
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
  api:
    hostname: datingapp-api
    container_name: datingapp-
    restart: on-failure
    build:
      context: .
      dockerfile: ./.Dockerfile
    environment: 
      Database__DdlConnectionString: "Host=postgres;Port=5432;Database=postgres;User Id=postgres;Password=postgres"
      Database__ConnectionString: "Host=postgres;Port=5432;Database=datingapp;User Id=postgres;Password=postgres"
      Database__Names: "datingapp"
    depends_on: 
      - postgres
    ports:
      - "10001:80"